### ISSUE TITLE
SARS-CoV-2-RBD_Omicron_MAP_LY-CoV1404 is 404

### ISSUE THREAD

**Issue by KaimingTao** [jbloomlab/SARS-CoV-2-RBD_DMS_Omicron#2]
Thanks for sharing your binding and expression data of Omicron variants in your new preprint, 10.1101/2022.09.20.508745.

When reading the paper, I found the repo of Bebtelovimab is 404, https://github.com/jbloomlab/SARS-CoV-2-RBD_Omicron_MAP_LY-CoV1404.

**Comment by jbloom** [comment]
Sorry, we had forgotten to make that repo public. It is now available at https://github.com/jbloomlab/SARS-CoV-2-RBD_Omicron_MAP_LY-CoV1404

**Comment by KaimingTao** [comment]
@jbloom, many thanks!
